[workspace]
members = [
  "crates/nanocl_stubs",
  "crates/nanocld_client",
  "bin/ctrl-proxy",
  "bin/ctrl-dns",
  "bin/nanocld",
  "bin/nanocl",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 'z'
codegen-units = 1
strip = "debuginfo"

[patch.crates-io]
nanocl_stubs = { path = "crates/nanocl_stubs" }
nanocld_client = { path = "crates/nanocld_client" }
ntex-files = { git = "https://github.com/leon3s/ntex-extras", branch = "upgrade-ntex-version" }
# ntex-multipart = { git = "https://github.com/leon3s/ntex-extras" }
# bollard-next = { path = "../bollard" }
#ntex = { git = "https://github.com/ntex-rs/ntex" }
#ntex-tokio = { git = "https://github.com/ntex-rs/ntex" }
