# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "ctrl-proxy"
version = "0.2.4"
edition = "2021"
authors = ["nanocl contributors <team@next-hat.com>"]
description = "The Self-Sufficient Hybrid-Cloud Orchestrator Daemon"
readme = "readme.md"
license = "MIT OR Apache-2.0"
homepage = "https://docs.next-hat.com/docs/guides/nanocl/overview"
repository = "https://github.com/nxthat/nanocld"

[[bin]]
name = "ctrl-proxy"
test = true
bench = false
path = "src/main.rs"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.19"
serde_json = "1.0.91"

[dev-dependencies]
bollard-next = "0.14.4"
serde_yaml = "0.9.19"

[dependencies]
clap = { version = "4.1.7", features = ["derive"] }
ntex = { version = "0.6.5", features = ["tokio"] }
nanocld_client = { version = "0.4.1" }
serde_json = "1.0.91"
futures = "0.3.25"
log = "0.4.17"
env_logger = "0.10.0"
serde = "1.0.154"
