[package]
name = "nanocl_stubs"
version = "0.6.1"
edition = "2021"
authors = ["nanocl contributors <team@next-hat.com>"]
description = "Nanocl shared data model"
readme = "readme.md"
license = "MIT OR Apache-2.0"
homepage = "https://docs.next-hat.com/docs/guides/nanocl/overview"
repository = "https://github.com/nxthat/nanocl"

[lib]
bench = false

[features]
serde = ["dep:serde", "uuid/serde", "chrono/serde"]
utoipa = ["dep:utoipa"]

[dependencies]
bollard-next = { version = "0.14.9" }
uuid = { version = "1.2.2" }
serde_json = "1.0.91"
chrono = { version = "0.4.24", default-features = false, features = [
  "std",
  "clock",
] }
serde = { version = "1.0.152", features = ["derive"], optional = true }
utoipa = { version = "3", features = ["uuid", "chrono"], optional = true }
