name: Publish Image

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release_image:
    runs-on: ubuntu-latest

    steps:
      - name: Get info
        run: |
          echo "BINARY_NAME=$(echo ${{ github.event.release.name }} | awk -F- '{print $1}')" >> $GITHUB_ENV
          echo "CHANNEL=$(echo ${{ github.event.release.name }} | awk -F- '{print $3}')" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.event.release.name }} | awk -F- '{print $2}')" >> $GITHUB_ENV
      - name: Print info
        run: |
          echo $BINARY_NAME
          echo $CHANNEL
          echo $VERSION
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_TOKEN }}
      - name: Publish Nightly
        if: env.CHANNEL == 'nightly'
        run: |
          gh release download -R next-hat/nanocl $BINARY_NAME-$VERSION-nightly -p $BINARY_NAME-$VERSION-nightly.tar.gz
          cat $BINARY_NAME-$VERSION-nightly.tar.gz | docker load
          docker tag ghcr.io/next-hat/$BINARY_NAME:$VERSION-nightly ghcr.io/next-hat/$BINARY_NAME:nightly
          docker tag ghcr.io/next-hat/$BINARY_NAME:$VERSION-nightly ghcr.io/next-hat/$BINARY_NAME:$VERSION-nightly
          docker push ghcr.io/next-hat/$BINARY_NAME:nightly
          docker push ghcr.io/next-hat/$BINARY_NAME:$VERSION-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Publish Stable
        if: env.CHANNEL != 'nightly'
        run: |
          gh release download -R next-hat/nanocl $BINARY_NAME-$VERSION -p $BINARY_NAME-$VERSION.tar.gz
          cat $BINARY_NAME-$VERSION.tar.gz | docker load
          docker tag ghcr.io/next-hat/$BINARY_NAME:$VERSION ghcr.io/next-hat/$BINARY_NAME:latest
          docker tag ghcr.io/next-hat/$BINARY_NAME:$VERSION ghcr.io/next-hat/$BINARY_NAME:$VERSION
          docker push ghcr.io/next-hat/$BINARY_NAME:latest
          docker push ghcr.io/next-hat/$BINARY_NAME:$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
